// src/components/products/product-data.ts
// src/components/products/product-data.ts
export const mockProducts = [
  {
    id: "prod_1",
    name: "Carrara White",
    category: "Floor Tiles",
    variant: "600x600mm Glossy",
    uom: "Box (1.44 sqm)",
    stock: 35,
    supplier: "Kajaria",
  },
  {
    id: "prod_2",
    name: "Hexa Matte Grey",
    category: "Wall Tiles",
    variant: "300x450mm Matte",
    uom: "Box (1.35 sqm)",
    stock: 10,
    supplier: "Somany",
  },
  {
    id: "prod_3",
    name: "Moroccan Blue",
    category: "Wall Tiles",
    variant: "250x375mm Glossy",
    uom: "Box (1.2 sqm)",
    stock: 5,
    supplier: "Nitco",
  },
  {
    id: "prod_4",
    name: "Subway White",
    category: "Wall Tiles",
    variant: "100x300mm Glossy",
    uom: "Box (1 sqm)",
    stock: 12,
    supplier: "Johnson",
  },
  {
    id: "prod_5",
    name: "Superflex Adhesive Grey",
    category: "Adhesives",
    variant: "20kg Bag",
    uom: "Bag",
    stock: 8,
    supplier: "MYK Laticrete",
  },
  {
    id: "prod_6",
    name: "Marble Look Beige",
    category: "Floor Tiles",
    variant: "800x800mm Glossy",
    uom: "Box (1.28 sqm)",
    stock: 0,
    supplier: "Kajaria",
  },
  {
    id: "prod_7",
    name: "Notched Trowel 8mm",
    category: "Tools",
    variant: "Stainless Steel",
    uom: "Piece",
    stock: 20,
    supplier: "Cera Tools",
  },
  {
    id: "prod_8",
    name: "Grout White",
    category: "Adhesives",
    variant: "5kg Pack",
    uom: "Bag",
    stock: 15,
    supplier: "Roff",
  },
  {
    id: "prod_9",
    name: "Anti-Skid Black",
    category: "Floor Tiles",
    variant: "300x300mm Matte",
    uom: "Box (0.9 sqm)",
    stock: 9,
    supplier: "Nitco",
  },
  {
    id: "prod_10",
    name: "Silicone Sealer Transparent",
    category: "Tools",
    variant: "300ml Tube",
    uom: "Piece",
    stock: 4,
    supplier: "Dr. Fixit",
  },
  {
    id: "prod_11",
    name: "Terracotta Rustic",
    category: "Wall Tiles",
    variant: "300x600mm Matte",
    uom: "Box (1.2 sqm)",
    stock: 18,
    supplier: "Somany",
  },
  {
    id: "prod_12",
    name: "Primer Plus",
    category: "Adhesives",
    variant: "1L Bottle",
    uom: "Bottle",
    stock: 6,
    supplier: "MYK Laticrete",
  },
  {
    id: "prod_13",
    name: "Tile Spacer 2mm",
    category: "Tools",
    variant: "Pack of 100",
    uom: "Pack",
    stock: 25,
    supplier: "Cera Tools",
  },
  {
    id: "prod_14",
    name: "Glossy Porcelain Grey",
    category: "Floor Tiles",
    variant: "600x1200mm",
    uom: "Box (1.44 sqm)",
    stock: 11,
    supplier: "Kajaria",
  },
  {
    id: "prod_15",
    name: "Leveling Clips",
    category: "Tools",
    variant: "100 pcs pack",
    uom: "Pack",
    stock: 2,
    supplier: "Cera Tools",
  },
  {
    id: "prod_16",
    name: "Slate Textured Black",
    category: "Wall Tiles",
    variant: "300x600mm",
    uom: "Box (1.2 sqm)",
    stock: 7,
    supplier: "Johnson",
  },
  {
    id: "prod_17",
    name: "Rough Surface Cleaner",
    category: "Tools",
    variant: "1L",
    uom: "Bottle",
    stock: 13,
    supplier: "Roff",
  },
  {
    id: "prod_18",
    name: "Teak Wood Plank Tile",
    category: "Floor Tiles",
    variant: "200x1200mm",
    uom: "Box (1.2 sqm)",
    stock: 22,
    supplier: "Somany",
  },
  {
    id: "prod_19",
    name: "Wall Putty",
    category: "Adhesives",
    variant: "20kg Bag",
    uom: "Bag",
    stock: 3,
    supplier: "JK Cement",
  },
  {
    id: "prod_20",
    name: "Tile Cutter Blade",
    category: "Tools",
    variant: "110mm",
    uom: "Piece",
    stock: 30,
    supplier: "Bosch",
  },
  {
    id: "prod_21",
    name: "Skirting Tile White",
    category: "Floor Tiles",
    variant: "100x600mm",
    uom: "Box (1.1 sqm)",
    stock: 13,
    supplier: "Kajaria",
  },
  {
    id: "prod_22",
    name: "Mosaic Multicolor",
    category: "Wall Tiles",
    variant: "Glass Sheet 30x30cm",
    uom: "Sheet",
    stock: 6,
    supplier: "OrientBell",
  },
  {
    id: "prod_23",
    name: "Manual Tile Cutter",
    category: "Tools",
    variant: "600mm",
    uom: "Piece",
    stock: 9,
    supplier: "Bosch",
  },
  {
    id: "prod_24",
    name: "Epoxy Grout Silver",
    category: "Adhesives",
    variant: "2kg Kit",
    uom: "Box",
    stock: 5,
    supplier: "Roff",
  },
  {
    id: "prod_25",
    name: "Matt Finish White",
    category: "Wall Tiles",
    variant: "300x450mm",
    uom: "Box (1.35 sqm)",
    stock: 8,
    supplier: "Johnson",
  },
  {
    id: "prod_26",
    name: "Ceramic Sink Square",
    category: "Sanitaryware",
    variant: "400x400mm",
    uom: "Piece",
    stock: 12,
    supplier: "Cera",
  },
  {
    id: "prod_27",
    name: "Wall Hung WC",
    category: "Sanitaryware",
    variant: "Standard Size",
    uom: "Piece",
    stock: 17,
    supplier: "Hindware",
  },
  {
    id: "prod_28",
    name: "Rapid Tile Adhesive",
    category: "Adhesives",
    variant: "25kg",
    uom: "Bag",
    stock: 14,
    supplier: "MYK Laticrete",
  },
  {
    id: "prod_29",
    name: "Tile Polish Gloss",
    category: "Tools",
    variant: "500ml Spray",
    uom: "Bottle",
    stock: 7,
    supplier: "Roff",
  },
  {
    id: "prod_30",
    name: "Travertine Gold",
    category: "Floor Tiles",
    variant: "600x1200mm Natural",
    uom: "Box (1.44 sqm)",
    stock: 6,
    supplier: "Nitco",
  },
];
